version: '3.9'

services:
  web:
    build: ./chicago-raw-food-app
    container_name: sveltekit_app
    # Map host port 3000 to container port 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      # Environment variables for your SvelteKit app
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE_NAME: example
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data: